name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Build Cross
        run: make cross

      - name: Ship it
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          prerelease: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}